all: 1b 4 5a 5b 6a 6b 6c 10 11a 11b 11c 12

1b: ./ex1/1b.c
	cc ./ex1/1b.c -o ./ex1/1b

4: ./ex4/4.c
	cc -static -Wall ./ex4/4.c -o ./ex4/4

5a: ./ex5/5a.c
	cc ./ex5/5a.c -Wall -o ./ex5/5a

5b: ./ex5/5b.c
	cc ./ex5/5b.c -Wall -o ./ex5/5b

6a: ./ex6/6a.c
	cc ./ex6/6a.c -o ./ex6/6a

6b: ./ex6/6b.c
	cc ./ex6/6b.c -o ./ex6/6b

6c: ./ex6/6c.c
	cc ./ex6/6c.c -o ./ex6/6c

10: ./ex10/10.c
	cc ./ex10/10.c -Wall -o ./ex10/10

11a: ./ex11/11a.c
	cc ./ex11/11a.c -o ./ex11/11a

11b: ./ex11/11b.c
	cc ./ex11/11b.c -Wall -o ./ex11/11b

11c: ./ex11/11c.c
	cc ./ex11/11c.c -Wall -o ./ex11/11c

12: ./ex12/12.c
	cc ./ex12/12.c -Wall -o ./ex12/12

clean:
	rm -f ./ex1/1b ./ex4/4 ./ex5/5a ./ex5/5b ./ex6/6a ./ex6/6b ./ex6/6c ./ex10/10 ./ex11/11a ./ex11/11b ./ex11/11c ./ex12/12